### ISSUE TITLE
Feature request: region name in file name

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Geomaker#2]
Currently the downloaded files are stored using a random string of symbols;  i.e. `$HOME/.local/share/geomaker/DOM10/747a846b3ec55e55212065e1d8690cbbfcabb91d461d18eb78f99857a274995f.tiff`. Could this be changed so the filename reflects the region name given in the GUI.

**Comment by VikingScientist** [comment]
There is currently no way to distinguish between downloaded `.tiff`-files. Is it possible to get a quick fix where either
* Thumbnail `.png` images have matching filename as the `.tiff`map files, or
* The filename is shown somewhere in the user interface

Currently I have 3 files in the DTM10-folder:
* 1d0892abd0f9caced995fbfaf6e05f3277205e4c3907aee16c2f2963ebf97367.tiff
* e87d9cbba0ff9724bc315ee9d4b12582787956c1768bd6530ddfdf123bd693f0.tiff
* f32669d118f802e7b966b5918fd3d5cc1bb418b303ad1ab962f70286160901c6.tiff

and no way of separating these, save to load them in a separate 3rd party tiff-viewer

**Comment by TheBB** [comment]
I'll try to get something for you. There's no one-to-one correspondence between tiff files and polygons/thumbnails so I was thinking just to have a 'export' feature in the software itself. It's not so easy just to say they should have the same filenames. :-/

For now you can try this:

```bash
sqlite3 -line ~/.local/share/geomaker/db.sqlite3 'select polygon.name, geotiff.filename from polygon, geotiff, polytiff where polygon.id = polytiff.polygon_id and geotiff.id = polytiff.geotiff_id;'
```

**Comment by VikingScientist** [comment]
sqlite3 hack confirmed to work. I am for the moment content :smiley_cat:

**Comment by VikingScientist** [comment]
sqlite3 hack doesn't work anymore :(

**Comment by TheBB** [comment]
Sorry. I renamed some tables. This should work.    

    sqlite3 -line ~/.local/share/geomaker/db.sqlite3 'select polygon.name, datafile.filename from polygon, datafile, polydata where polygon.id = polydata.polygon_id and datafile.id = polydata.datafile_id;'

**Comment by VikingScientist** [comment]
Geomaker does have an export to geoTIFF now, so I guess this is no longer relevant.
