### ISSUE TITLE
Feature request: aerial photo zoom level relative to interactive map

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Geomaker#37]
Zoom level 1-16 is hard to interpret, and so I would like that the default value set what is currently used in the background map. One might then take an educated decision on wheter to increase or decrease this by a couple of levels

![Workspace 1_007](https://user-images.githubusercontent.com/3500376/75018145-aa736580-548e-11ea-9f5d-e521ba0667b5.png)

**Comment by VikingScientist** [comment]
The zoom value is available from what I assume is here

https://github.com/SINTEF/Geomaker/blob/5f4a741bc95c315a2173b6728f1174a726f1165b/geomaker/db.py#L533-L539

Just have to figure a way to pass this to the `JobDialog` object.

**Comment by TheBB** [comment]
Well, not exactly. The zoom level must exist somewhere in the Javascript program running in the embedded web browser. We have to get it from there.
